project:
  type: book
  output-dir: docs

book:
  title: "PHCM9795: Foundations of Biostatistics"
  author: "Timothy Dobbins"
  date: "24-Jul-2025"
  date-format: "DD MMMM, YYYY"
  version: 1.0
  chapters:
    - index.qmd
    # - 01-intro.qmd
    # - 02-probability.qmd
    # - 03-precision.qmd
    # - 04-hypothesis-testing.qmd
    # - 05-comparing-two-means.qmd
    # - 06-proportions.qmd
    # - 07-testing-proportions.qmd
    # - 08-correlation-and-regression.qmd
    # - 09-non-parametrics.qmd
    # - 10-sample-size.qmd
    # - 98.1-appendix1.qmd
    # - references.qmd

bibliography: PHCM9795.bib

pdf-engine: xelatex

format:
  html:
    theme: zephyr
    highlight-style: monochrome
    title-block-banner: "#ffdc00"
    number-depth: 2
  # pdf:
  #   papersize: A4
  #   documentclass: memoir
  #   mainfont: Roboto
  #   sansfont: Clancy
  #   include-in-header: preamble.tex
  #   highlight-style: monochrome

